data:
  root: data/baboon
  resolution: 64
  subset:
model:
  spectrum_disc: False
training:
  batch_size: 10
  nworkers: 0
  monitoring: tensorboard
  nepochs: 10000
  print_every: 100
  eval_every: 100
  save_every: 5000
  lr_g: 0.01
  lr_d: 0.001
  reg_param: 10.
  model_average_beta: 0.999
  lr_decay_epochs: 0
  lr_decay_every_n_steps: 100
  lr_decay_rate: 1.0  # set to < 1.0 to apply lr decay across the last lr_decay_epochs.
  criterion:
    class_name: torch.nn.BCEWithLogitsLoss
    weight:
  model_file: model.pt
  seed: 0
