model:
  class_name: models.SG2WaveletGenerator
  z_dim: 64
  divide_channels_by: 8
  architecture: skip
  upscale_bilinear: true
  normalize_dwt: true
#   downsampling_mode: avg
#   padding_mode: zeros
# training:
  # lr_decay_epochs: 2000
  # lr_decay_every_n_steps: 100
  # lr_decay_rate: 0.75
data:
  highpass: false
